[[CUDA_SDK]]
arch = "x86_64"
git-tree-sha1 = "c1f0089a873386b1245d9a851bc824f21fa6c684"
libc = "glibc"
os = "linux"

    [[CUDA_SDK.download]]
    sha256 = "54021addece1bdd9bf85d5eae04d0fa94aca4a91ff512b2ee540ba2d46bf065a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_SDK_jll.jl/releases/download/CUDA_SDK-v13.1.1+0/CUDA_SDK.v13.1.1.x86_64-linux-gnu.tar.xz"
[[CUDA_SDK]]
arch = "aarch64"
git-tree-sha1 = "76cf3c7b4661646a18e44c42dc508573835ad4b0"
libc = "glibc"
os = "linux"

    [[CUDA_SDK.download]]
    sha256 = "890365a220d3592de2f5574e629be56b6135cd4853bf1500e5f4b9f86adb0e72"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_SDK_jll.jl/releases/download/CUDA_SDK-v13.1.1+0/CUDA_SDK.v13.1.1.aarch64-linux-gnu.tar.xz"
[[CUDA_SDK]]
arch = "x86_64"
git-tree-sha1 = "106bf36be3e6717e70f0de402806aa570da48317"
os = "windows"

    [[CUDA_SDK.download]]
    sha256 = "ae3e83fde99b27b9225ac9821db2dae071bc80c4d3a8feb6965f0bc076abadd9"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_SDK_jll.jl/releases/download/CUDA_SDK-v13.1.1+0/CUDA_SDK.v13.1.1.x86_64-w64-mingw32.tar.xz"
